/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/analise`; params?: Router.UnknownInputParams; } | { pathname: `/apoio`; params?: Router.UnknownInputParams; } | { pathname: `/carregando`; params?: Router.UnknownInputParams; } | { pathname: `/configuracoes`; params?: Router.UnknownInputParams; } | { pathname: `/criar-conta`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/sobre`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/favorito` | `/favorito`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/historico` | `/historico`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/perfil` | `/perfil`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/recomendacao` | `/recomendacao`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/analise`; params?: Router.UnknownOutputParams; } | { pathname: `/apoio`; params?: Router.UnknownOutputParams; } | { pathname: `/carregando`; params?: Router.UnknownOutputParams; } | { pathname: `/configuracoes`; params?: Router.UnknownOutputParams; } | { pathname: `/criar-conta`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/sobre`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/favorito` | `/favorito`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/historico` | `/historico`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/perfil` | `/perfil`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/recomendacao` | `/recomendacao`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/analise${`?${string}` | `#${string}` | ''}` | `/apoio${`?${string}` | `#${string}` | ''}` | `/carregando${`?${string}` | `#${string}` | ''}` | `/configuracoes${`?${string}` | `#${string}` | ''}` | `/criar-conta${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/modal${`?${string}` | `#${string}` | ''}` | `/sobre${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/favorito${`?${string}` | `#${string}` | ''}` | `/favorito${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/historico${`?${string}` | `#${string}` | ''}` | `/historico${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/perfil${`?${string}` | `#${string}` | ''}` | `/perfil${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/recomendacao${`?${string}` | `#${string}` | ''}` | `/recomendacao${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/analise`; params?: Router.UnknownInputParams; } | { pathname: `/apoio`; params?: Router.UnknownInputParams; } | { pathname: `/carregando`; params?: Router.UnknownInputParams; } | { pathname: `/configuracoes`; params?: Router.UnknownInputParams; } | { pathname: `/criar-conta`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/sobre`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/favorito` | `/favorito`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/historico` | `/historico`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/perfil` | `/perfil`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/recomendacao` | `/recomendacao`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
